export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
// rootlayout가 export default되어 있고, metadata는 export만 되고 있음
// 당연 하게도 default export 객체는 하나만 지정 할수 있기 때문

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
